### ISSUE TITLE
Algorytm grahama - "USUNĄĆ GŁUPOTKI Z COMMITA"

### ISSUE THREAD

**Issue by migoox** [migoox/aisd-notatki#32]
![image](https://github.com/migoox/aisd-notatki/assets/56317134/61976aea-ac06-4a43-a3da-910d1f675e23)
o co chodzi?
piszmy takie rzeczy na issue, bo wtedy nie wiadomo o co chodzi

**Comment by mslup** [comment]
sorki! to był tymczasowy komentarz dla mnie który nie miał się znaleźć w tym commicie XD w następnym commicie usunąłem notatkę
