### ISSUE TITLE
Pisownia `true` i `false`

### ISSUE THREAD

**Issue by mslup** [migoox/aisd-notatki#42]
Pierdoła, czyli coś co lubię najbardziej. Zastanawiałem się i najbardziej podobało mi się rozwiązanie pisania `true` i `false` kursywą w tekście, ale pismem prostym w algorytmach, no ale to trochę głupie, więc poszedłem na kompromis (czyli żadną z dwóch opcji): proponuję pismem bezszeryfowym wszędzie.

`\textit{...}`
![image](https://github.com/migoox/aisd-notatki/assets/132074948/d75979cf-5b88-42c5-8bf4-6fdc122a8677)

`\textsf{...}`
![image](https://github.com/migoox/aisd-notatki/assets/132074948/0e90b13e-2ad1-46ec-8608-d80e59ef2d69)

@migoox powiedz co myślisz, jeśli podoba ci się to zmienię wszędzie i zachęcam do stosowania :3

~~...gorzej będzie jeżeli przestanie mi się podobać~~

**Comment by migoox** [comment]
Wydaje mi sie, że \textit bardziej wyglada jak nazwa jakiejs zmiennej, a\textsf bardziej jak wartość, idk., ja bym robil \textsf, zparaszam @kubazuch do dyskusji
