### ISSUE TITLE
Numerowanie zadań

### ISSUE THREAD

**Issue by mslup** [migoox/aisd-notatki#52]
Może nie numerujmy zadań? Jest to moim zdaniem reduntantne, bo mamy już numery sekcji, do których możemy się odwoływać (i które będą automatycznie się aktualizowały). Numer zadania z kartki (który w przyszłych latach może się zmienić) można umieścić w treści w nawiasie. W spisie treści wprowadza to moim zdaniem trochę za dużo bałaganu

![image](https://github.com/migoox/aisd-notatki/assets/132074948/a88f2e55-b454-47aa-ab92-b33c13bdc704)

![image](https://github.com/migoox/aisd-notatki/assets/132074948/fa5320ae-2cd3-4436-a933-8df34634e598)

Co myślicie? @migoox @kubazuch

**Comment by kubazuch** [comment]
Myślę że mi wszystko to jedno
Purr

**Comment by kubazuch** [comment]
w sumie chciałbym po spisie treści chcieć znaleźć szybko zadanie którego szukam

**Comment by migoox** [comment]
w sensie to by mialo sens gdyby to nie byly notatki do studiów, bo jak chcesz znaleźć zadanie ktore cie interesuje to zazwyczaj bedziesz patrzyl po numerku, wiec ja bym zostawil

mozna ewentualnie dodać jakiś nawias na koncu tresci typu Szukanie podzbioru o zadanej sumie elementów (Zadanie 1.1)
