### ISSUE TITLE
Poprawić nieścisłości w Grahamie

### ISSUE THREAD

**Issue by mslup** [migoox/aisd-notatki#54]
- dlaczego pokazujemy że P[0] jest punktem CH? 
- "który jest otoczką zbioru P" -> "zbioru P od 0 do k-1"
- podpis obrazka (współliniowe)
- przechodniość prawoskrętności ;;;----)))) w (c)

**Comment by migoox** [comment]
"dlaczego pokazujemy że P[0] jest punktem CH?" odnosi sie do tego ze powinnismy napisac to notatkach, czy to jest po prostu pytanie?

**Comment by migoox** [comment]
i jeszcze zastanawiam sie czy nie lepiej byloby rozbic ten krok indukcyjny, na 
- dowód, że $S_k$ jest wielokątem wypukłym bez samoprzecięć - (a) + (b)
- dowód, że wielokąt wypukły $S_k$ jest otoczką - (c)
tzn. uwazam ze dobrze to podkreslic, np. po wykonaniu podpunktów (a) i (b)

**Comment by mslup** [comment]
> "dlaczego pokazujemy że P[0] jest punktem CH?" odnosi sie do tego ze powinnismy napisac to notatkach, czy to jest po prostu pytanie?
> 
> 

powinniśmy napisać

**Comment by mslup** [comment]
> i jeszcze zastanawiam sie czy nie lepiej byloby rozbic ten krok indukcyjny, na 
> 
> - dowód, że $S_k$ jest wielokątem wypukłym bez samoprzecięć - (a) + (b)
> 
> - dowód, że wielokąt wypukły $S_k$ jest otoczką - (c)
> 
> tzn. uwazam ze dobrze to podkreslic, np. po wykonaniu podpunktów (a) i (b)

można
