### ISSUE TITLE
Poprawić nieścisłości w KMP

### ISSUE THREAD

**Issue by mslup** [migoox/aisd-notatki#55]
- w dowodzie poprawności ComputeP powinna być silna indukcja
- krok indukcyjny, 2 akapit: W petli while (...)x'.  Z zał. ind. są wyznaczone poprawnie
- po cases w przypadku gdy $T'$ puste: "zatem wartość jest poprawne"
- złożoność computeP: "niedeterministyczną"
- złożoność computeP: "jako, że"
- w złożoności KMP "jako, że"

**Comment by migoox** [comment]
nie do konca rozumiem w jaki sposob korzystamu tutaj z 13.1 
![image](https://github.com/migoox/aisd-notatki/assets/56317134/5d879258-0e53-469f-a39f-0f3d5008e567)

w sensie ja to widze moze inaczej, ale still wole sie upewnic

**Comment by kubazuch** [comment]
wiecie co może nawet to zrobię

**Comment by kubazuch** [comment]
> nie do konca rozumiem w jaki sposob korzystamu tutaj z 13.1 ![image](https://user-images.githubusercontent.com/56317134/247086592-5d879258-0e53-469f-a39f-0f3d5008e567.png)
> 
> w sensie ja to widze moze inaczej, ale still wole sie upewnic

13.1 mówi że w tekście na pozycji k stoi cały wzorzec. Z kolei $tekst[k\dots i+j-1]=wzorzec[0\dots j-1-k']$ to wykorzystanie tylko $j-k'$ (uwaga od 0 do k jest k+1 znaków!!!) pierwszych znaków tej zależności, bo wtedy bierzemy z tekstu fragment $tekst[k\dots k+j-1-k']=tekst[k\dots k+j-1-(k-i)]=tekst[k\dots i+j-1]$, a z wzorca $wzorzec[0\dots j-1-k']$ 😊
